# https://docs.travis-ci.com/user/deployment/script/
# deploy:
#   provider: script
#   script: bash scripts/hello.sh
#   on:
#     branch: master

# https://docs.travis-ci.com/user/build-stages/
# jobs:  
#   include:
#     - stage: "Hello World"                # naming the Tests stage
#       name: "say HI"            # names the first Tests stage job
#       script: ./unit-tests
#     - script: ./integration-tests   
#       name: "Integration Tests"     # names the second Tests stage job
#     - stage: deploy
#       name: "Deploy to GCP"
#       script: ./deploy

# https://docs.travis-ci.com/user/deployment/pages/
language: generic
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master