# https://docs.travis-ci.com/user/deployment/pages/

os: osx
language: generic
script: ./scripts/convert.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: toCopy
  on:
    branch: master