name: lambda-redis-client
version: 0.0.1
id: 4bdf6d48-2220-414b-8818-85d90ae3975c
description: "Lambda redis client by Helm Broker (Experimental)"
displayName: "lambda redis client"

tags: test, lambda
providerDisplayName: PK
longDescription: "Lambda redis client by Helm Broker (Experimental)"
documentationURL: https://todo.com/
supportURL: https://todo.com/
imageURL: https://todo.com/
bindable: false
