name: lambda-rc
version: 0.0.1
id: 4bdf6d48-2220-414b-8818-85d90ae3975c
description: "Lambda which uses redis client - by Helm Broker (Experimental)"
displayName: "Function with Redis Client"

tags: helm-broker, showcase, lambda
providerDisplayName: PK
longDescription: "Long Description: Lambda which uses redis client - by Helm Broker (Experimental)"
documentationURL: https://todo.com/
supportURL: https://todo.com/
imageURL: https://todo.com/
bindable: false
